name: Pipeline CI/CD Completo

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  teste-de-titulo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Imprime o HTML no log
        run: cat index.html
        
      - name: Fiscal linha dura
        run: |
          if grep -q "<title>" index.html; then
            echo "Opa, achei a tag title! Passando..."
            exit 0
          else
            echo "Erro: KD a tag title mano?? Bloqueando!"
            exit 1
          fi

  deploy-site:
    needs: teste-de-titulo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Publica no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4